from flask import Flask, jsonify, request
from flask_cors import CORS
import pandas as pd
import os
import requests
import json  

app = Flask(__name__)
CORS(app)

CSV_PATH = os.path.join(os.path.dirname(__file__), "archive", "box_scores", "Games.csv")


@app.route('/api/historical-data')
def get_historical_data():
    game_date = request.args.get('date')
    try:
        # load the necessary columns, matching your CSV
        df = pd.read_csv(CSV_PATH, usecols=[
            'gameDateTimeEst', 'hometeamName', 'awayteamName', 'homeScore', 'awayScore'
        ])

        df = df.rename(columns={'gameDateTimeEst': 'gameDate'})

        df['gameDateOnly'] = df['gameDate'].astype(str).str.split(' ').str[0]

        if game_date:
            filtered = df[df['gameDateOnly'] == game_date]
        else:
            filtered = df

        # Sort recent first
        filtered = filtered.sort_values("gameDate", ascending=False)

        games_list = []
        for idx, row in filtered.iterrows():
            games_list.append({
                "game_date": row['gameDateOnly'],
                "team_name_home": row['hometeamName'],
                "team_name_away": row['awayteamName'],
                "pts_home": row['homeScore'],
                "pts_away": row['awayScore'],
            })

        return jsonify(games_list if game_date else games_list[:20])
    except Exception as e:
        print("Data error:", e)
        return jsonify({"error": str(e)}), 500


@app.route('/api/live-nba-odds')
def get_live_nba_odds():
    try:
        # We now read the file generated by daily_update.py
        json_path = os.path.join(os.path.dirname(__file__), 'todays_data.json')
        
        with open(json_path, 'r') as f:
            data = json.load(f)
            
        # The file contains {"games": [...], "last_updated": ...}
        # The frontend expects just the list of games, so we send data['games']
        return jsonify(data['games'])

    except FileNotFoundError:
        return jsonify({"error": "No daily data found. Run daily_update.py first."}), 404
    except Exception as e:
        print("Error serving batch data:", e)
        return jsonify({"error": str(e)}), 500


@app.route('/api/player-props')
def get_player_props():
    """
    Returns simplified NBA player props for today's games.
    """
    API_KEY = '39fc4ed3a7caf51b49d87d08ec90658a'
    ODDS_API_URL = "https://api.the-odds-api.com/v4/sports/basketball_nba/odds"

    player_markets = [
        "player_points",
        "player_rebounds",
        "player_assists",
        "player_threes",
        "player_points_rebounds_assists",
    ]

    params = {
        "regions": "us",
        "markets": ",".join(player_markets),
        "oddsFormat": "american",
        "apiKey": API_KEY
    }

    try:
        resp = requests.get(ODDS_API_URL, params=params, timeout=10)
        resp.raise_for_status()
        events = resp.json()
    except requests.RequestException as e:
        print("Player props API error:", e)
        return jsonify({"error": str(e)}), 500

    simplified = []

    for event in events:
        game_id = event.get("id")
        home_team = event.get("home_team")
        away_team = event.get("away_team")
        commence_time = event.get("commence_time")

        for bookmaker in event.get("bookmakers", []):
            book_key = bookmaker.get("key")
            book_title = bookmaker.get("title")

            for market in bookmaker.get("markets", []):
                market_key = market.get("key")
                if market_key not in player_markets:
                    continue

                for outcome in market.get("outcomes", []):
                    player_name = outcome.get("description") or outcome.get("name")
                    line = outcome.get("point")
                    price = outcome.get("price")

                    simplified.append({
                        "game_id": game_id,
                        "home_team": home_team,
                        "away_team": away_team,
                        "commence_time": commence_time,
                        "bookmaker": book_title or book_key,
                        "market": market_key,
                        "player": player_name,
                        "line": line,
                        "price": price,
                        "openbet_flag": None  # for your model later
                    })

    return jsonify(simplified)


if __name__ == "__main__":
    # host='0.0.0.0' allows access from network, port 5050 matches your React app
    app.run(host="0.0.0.0", port=5050, debug=True)
