from flask import Flask, jsonify, request
from flask_cors import CORS
import pandas as pd
import os
import requests
import json  

app = Flask(__name__)
CORS(app)

CSV_PATH = os.path.join(os.path.dirname(__file__), "archive", "box_scores", "Games.csv")

@app.route('/api/historical-data')
def get_historical_data():
    game_date = request.args.get('date')
    try:
        # load the necessary columns, matching your CSV
        df = pd.read_csv(CSV_PATH, usecols=[
            'gameDateTimeEst', 'hometeamName', 'awayteamName', 'homeScore', 'awayScore'
        ])

        df = df.rename(columns={'gameDateTimeEst': 'gameDate'})

        df['gameDateOnly'] = df['gameDate'].astype(str).str.split(' ').str[0]

        if game_date:
            filtered = df[df['gameDateOnly'] == game_date]
        else:
            filtered = df

        # Sort recent first
        filtered = filtered.sort_values("gameDate", ascending=False)

        games_list = []
        for idx, row in filtered.iterrows():
            games_list.append({
                "game_date": row['gameDateOnly'],
                "team_name_home": row['hometeamName'],
                "team_name_away": row['awayteamName'],
                "pts_home": row['homeScore'],
                "pts_away": row['awayScore'],
            })

        return jsonify(games_list if game_date else games_list[:20])
    except Exception as e:
        print("Data error:", e)
        return jsonify({"error": str(e)}), 500

@app.route('/api/live-nba-odds')
def get_live_nba_odds():
    try:
        # We now read the file generated by daily_update.py
        json_path = os.path.join(os.path.dirname(__file__), 'todays_data.json')
        
        with open(json_path, 'r') as f:
            data = json.load(f)
            
        # The file contains {"games": [...], "last_updated": ...}
        # The frontend expects just the list of games, so we send data['games']
        return jsonify(data['games'])

    except FileNotFoundError:
        return jsonify({"error": "No daily data found. Run daily_update.py first."}), 404
    except Exception as e:
        print("Error serving batch data:", e)
        return jsonify({"error": str(e)}), 500

if __name__ == "__main__":
    # host='0.0.0.0' allows access from network, port 5050 matches your React app
    app.run(host="0.0.0.0", port=5050, debug=True)